// MilliStudiosOfficial — Central Data Store

export const team = [
  {
    id: "venkat",
    name: "Venkat Perumalla",
    role: "Founder",
    bio: "The driving visionary force. Venkat established MilliStudiosOfficial with a relentless ambition to push creative boundaries and tell profound stories.",
    specialties: ["Directing", "Creative Vision", "Leadership"],
    credits: ["Nija Chitram — Director", "MilliStudiosOfficial — Founder"],
    initials: "VP",
    accentColor: "#00eaff",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/trainwith__jay?igsh=dXNkODNxc2RzcWth",
    image: "/team-1.jpg"
  },
  {
    id: "poorna",
    name: "Poorna Penki",
    role: "Co-founder",
    bio: "Architecting the foundation. Poorna works alongside Venkat to steer the structural and creative trajectory of the studio's portfolio.",
    specialties: ["Operations", "Strategy", "Creative Producing"],
    credits: ["MilliStudiosOfficial — Co-founder", "Brand Strategy — Lead"],
    initials: "PP",
    accentColor: "#b22cff",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/_poorna_penki_?igsh=MTBjbTA5NzJiZm5kdg==",
    image: "/team-2.png"
  },
  {
    id: "subhani",
    name: "Subhani Basha SK",
    role: "CEO & Lead Cinematographer",
    bio: "The eye behind the lens and the operational lead. Subhani brings visual gravity to every frame while managing the studio's executive operations.",
    specialties: ["Cinematography", "Executive Leadership", "Color Grading"],
    credits: ["Nija Chitram — DOP", "Parichayamilla — Cinematography", "MilliStudiosOfficial — CEO"],
    initials: "SB",
    accentColor: "#a78bfa",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/__.bablu.__shaik?igsh=dW5odDNlczl6c3Zu",
    image: "/team-3.jpg"
  },
  {
    id: "saisurya",
    name: "Sai Surya Tej",
    role: "Project Manager",
    bio: "The core engine of production. Surya orchestrates the chaos of filmmaking into streamlined schedules and zero-delay execution.",
    specialties: ["Project Management", "Resource Planning", "Scheduling"],
    credits: ["Shortfilm Pipeline — Manager", "MilliStudiosOfficial — Core Team"],
    initials: "ST",
    accentColor: "#ffcc00",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/saisuryatej97?igsh=MWdydmNzczJ3Y3J2MQ==",
    image: "/team-4.jpg"
  },
  {
    id: "akhil",
    name: "Akhil Peddishetty",
    role: "Production Manager",
    bio: "Bridging the gap between technical logic and cinematic art. Akhil ensures every set, frame, and digital asset is assembled perfectly.",
    specialties: ["Production", "Technical Directing", "UI/UX & Unity"],
    credits: ["Oo Katha — Director", "Oo Priyathama — Visuals"],
    initials: "AP",
    accentColor: "#00ff73",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/_akhil__1?igsh=MzB2bzc1aGJhbHlh",
    image: "/team-5.jpg"
  },
  {
    id: "koushal",
    name: "Koushal Adepu",
    role: "Assistant Manager",
    bio: "The connective tissue on set. Koushal keeps the crews synchronized and the cameras rolling, acting as the ultimate tactical support.",
    specialties: ["On-Set Ops", "Crew Coordination", "Logistics"],
    credits: ["Location Logistics — Head", "Set Coordination"],
    initials: "KA",
    accentColor: "#ff2a2a",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/_koushal__4633?igsh=N25rYW41N3NiN2Z0",
    image: "/team-6.jpg"
  },
  {
    id: "dinesh",
    name: "Dinesh",
    role: "Assistant Manager",
    bio: "Master of details. Dinesh ensures no prop is misplaced and no schedule is broken, supporting the production from concept to wrap.",
    specialties: ["Management", "Pre-Production", "Tactical Support"],
    credits: ["Pre-Production Ops", "Crew Management"],
    initials: "DJ",
    accentColor: "#ff8c00",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/dineshjonnalagadda?igsh=MjVwNjdwYml1ZXpo",
    image: "/team-7.jpg"
  },
  {
    id: "arshad",
    name: "Arshad SK",
    role: "Designer",
    bio: "Crafting the visual identity. Arshad molds the branding, typography, and promotional aesthetics into a cohesive, aggressive Antigravity style.",
    specialties: ["UI/UX Design", "Graphic Design", "Brand Identity"],
    credits: ["MilliStudiosOfficial Branding", "Posters & VFX Graphics"],
    initials: "AS",
    accentColor: "#ff00ae",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/arshadux?igsh=eHl6bWVxaWVzZjU0",
    image: "/team-8.jpg"
  },
  {
    id: "dany",
    name: "Dany Orton",
    role: "Music Department",
    bio: "Architect of sound. Dany's original compositions breathe emotional life into every MilliStudiosOfficial production, fusing classical sensibility with cinematic scoring.",
    specialties: ["Composition", "Sound Design", "Audio Engineering"],
    credits: ["Oo Priyathama — Original Score", "Nee Gunde Lona — Production"],
    initials: "DO",
    accentColor: "#f9a8d4",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/jevadanreynolds?igsh=ZDFyZ2ViYXZycDhp",
    image: "/team-9.jpg"
  }
];

export const projects = [
  {
    id: "oo-katha",
    title: "Oo Katha",
    subtitle: "A Story",
    category: "Films",
    year: "10th Apr 2026",
    tags: ["Romance", "Short Film"],
    image: "/oo-katha-new.jpg",
    gradient: "linear-gradient(135deg, #1a0a00 0%, #0d0a1a 100%)",
    crew: { Director: "Subhani Basha", DOP: "Subhani Basha", Editor: "Subhani Basha" },
    link: "https://youtu.be/OeNyvRceGE0?si=jkPRE7v42-noOfkO",
    featured: true,
    emoji: "🎞",
  },
  {
    id: "nija-chitram",
    title: "Nija Chitram",
    subtitle: "The Real Face",
    category: "Films",
    year: "6th Apr 2026",
    tags: ["Feature Film", "Drama"],
    image: "/nija-chitram-new.jpg",
    gradient: "linear-gradient(135deg, #0a1e2a 0%, #0d1117 100%)",
    crew: { Director: "Akhil Peddishetty", DOP: "Subhani Basha", Editor: "Subhani Basha", Music: "Dany Orton" },
    link: "https://youtu.be/CV5iyEiO7vw?si=ec6KThExz6NilM1C",
    featured: true,
    emoji: "🎬",
  },
  {
    id: "nee-gunde-lona",
    title: "Nee Gunde Lona",
    subtitle: "A Heartfelt Cover",
    category: "Songs",
    subCategory: "Cover",
    year: "29th Dec 2025",
    tags: ["Cover Song", "Vocal"],
    image: "/nee-gunde-lona-new.jpg",
    gradient: "linear-gradient(135deg, #0a2e1a 0%, #0d0a1a 100%)",
    crew: { Director: "Sai Surya Tej", DOP: "Subhani Basha", Editor: "Subhani Basha" },
    link: "https://youtu.be/hmQ3L4D7Kc8?si=G8hQkfYrQ9u0pSjJ",
    featured: false,
    emoji: "🎙️",
  },
  {
    id: "sagipoo",
    title: "Sagipoo",
    subtitle: "Soulful Melody",
    category: "Songs",
    subCategory: "Own",
    year: "16th Oct 2025",
    tags: ["Music Video", "Cinematic"],
    image: "/sagipoo-new.jpg",
    gradient: "linear-gradient(135deg, #2e0a0a 0%, #0d0a1a 100%)",
    crew: { Director: "Subhani Basha", DOP: "Subhani Basha", Editor: "Subhani Basha", Music: "Dany Orton" },
    link: "https://youtu.be/Rkmh4RY1bzI?si=d7DA3l-cfv7x1TZT",
    featured: false,
    emoji: "🎵",
  },
  {
    id: "parichayamilla",
    title: "Parichayamilla",
    subtitle: "Musical Journey",
    category: "Songs",
    subCategory: "Cover",
    year: "29th Aug 2025",
    tags: ["Music Video", "Original"],
    image: "/parichayamilla-new.jpg",
    gradient: "linear-gradient(135deg, #0d0a1a 0%, #1a0a2e 100%)",
    crew: { Director: "Subhani Basha", DOP: "Subhani Basha", Editor: "Subhani Basha" },
    link: "https://youtu.be/w2lclbiT1to?si=nQkqlxH2ZVpjkgh-",
    featured: false,
    emoji: "🎶",
  },
  {
    id: "oo-priyathama",
    title: "Oo Priyathama",
    subtitle: "Original Composition",
    category: "Songs",
    subCategory: "Own",
    year: "19th Mar 2025",
    tags: ["Music Video", "Original Score"],
    image: "/oo-priyathama-new.jpg",
    gradient: "linear-gradient(135deg, #1a0a2e 0%, #0d1117 100%)",
    crew: { Director: "Venkat Perumalla", DOP: "Goutham & Sankalp", Editor: "Subhani Basha" },
    link: "https://youtu.be/nMbnC4PjpGc?si=WduAu3A0fALRXdC2",
    featured: true,
    emoji: "🎵",
  },
];

export const timeline = [
  {
    year: "2021",
    title: "KL University",
    desc: "B.Tech CSE begins. First experiments with Unity game development and React.js web applications.",
    icon: "🎓",
  },
  {
    year: "2022",
    title: "The Collective",
    desc: "Venkat, Poorna, and Subhani Basha begin collaborating on high-fidelity cinematic works.",
    icon: "🎬",
  },
  {
    year: "2022",
    title: "MilliStudiosOfficial Founded",
    desc: "Venkat Perumalla establishes MilliStudiosOfficial with a vision to defy creative gravity, bringing together a elite team of artists and technicians.",
    icon: "✦",
  },
  {
    year: "2023",
    title: "Nija Chitram",
    desc: "'The Real Face' — a full short film production. Professional crew, original script, studio-grade output.",
    icon: "🏆",
  },
  {
    year: "2023",
    title: "Oo Priyathama",
    desc: "Original music composition by Dany with visual direction by Akhil. MilliStudiosOfficial' first musical feature.",
    icon: "🎵",
  },
  {
    year: "2024",
    title: "Oo Katha & Production Scale",
    desc: "Release of 'Oo Katha' and the establishment of the full nine-member Team Milli roster.",
    icon: "⚡",
  },
  {
    year: "2025+",
    title: "Beyond Gravity",
    desc: "Feature films, brand collaborations, Antigravity game experiences. The next chapter is unwritten.",
    icon: "🚀",
  },
];

export const promotionalTeam = [
  {
    id: "promo-1",
    name: "Promoter Name 1",
    role: "Social Media Lead",
    bio: "Strategizing the digital reach. Leads the social media campaigns and engagement across all platforms.",
    specialties: ["Instagram Ads", "Audience Growth", "Strategy"],
    credits: ["MilliStudiosOfficial Launch", "Digital Campaign — Lead"],
    initials: "PN",
    accentColor: "#00eaff",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/millistudiosofficial/"
  },
  {
    id: "promo-2",
    name: "Promoter Name 2",
    role: "Outreach Coordinator",
    bio: "Connecting creators to the crowd. Manages the partnership and community outreach programs.",
    specialties: ["Community", "Partnerships", "Growth"],
    credits: ["Campaign Strategy", "Outreach Lead"],
    initials: "OC",
    accentColor: "#b22cff",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/millistudiosofficial/"
  },
  {
    id: "promo-3",
    name: "Promoter Name 3",
    role: "Brand Ambassador",
    bio: "The face of the brand. Represents the studio's values and vision in physical and digital spaces.",
    specialties: ["Public Relations", "Brand Voice", "Events"],
    credits: ["Live Events", "Brand Promotion"],
    initials: "BA",
    accentColor: "#ffcc00",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/millistudiosofficial/"
  },
  {
    id: "promo-4",
    name: "Promoter Name 4",
    role: "Digital Marketing",
    bio: "Molding the online presence. Executes the technical aspects of marketing and SEO optimization.",
    specialties: ["SEO", "AdWords", "Content Marketing"],
    credits: ["Web Growth", "SEO Strategy"],
    initials: "DM",
    accentColor: "#00ff73",
    edu: "MilliStudiosOfficial",
    instagram: "https://www.instagram.com/millistudiosofficial/"
  }
];
